import React from 'react';
import { FileText } from 'lucide-react';

export default function Footer() {
  return (
    <footer className="bg-gray-50 border-t">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="flex items-center justify-center mb-8">
          <FileText className="w-6 h-6 text-blue-600 mr-2" />
          <span className="text-lg font-semibold text-gray-900">BuellDocs</span>
        </div>
        
        <div className="text-center text-sm text-gray-600 max-w-4xl mx-auto">
          <p className="mb-4">
            All documents generated by BuellDocs are intended for novelty and educational purposes. 
            Users are solely responsible for the accuracy of the information they provide and for 
            using all generated documents in compliance with all applicable laws.
          </p>
          <p>&copy; 2025 BuellDocs. All rights reserved.</p>
        </div>
      </div>
    </footer>
  );
}